### ISSUE TITLE
Review UP 9

### ISSUE THREAD

**Issue by flowerornament** [urbit/proposals#7]
https://github.com/urbit/proposals/tree/up9

**Comment by msutherl** [comment]
@rmariani forgot about this. Did you want to make a PR, or submit to urbit-dev as RFC?

**Comment by rmariani** [comment]
This UP is outdated. I am unsure if Hoon School even needs a UP.

**Comment by msutherl** [comment]
@rmariani ok, sounds good – and agree I'm not sure it needs a UP
